spring:
  application:
    name: users-service
  grpc:
    client:
      channels:
        messages:
          negotiation-type: PLAINTEXT

keycloak:
  active: true
  master-realm: master
  master-client: admin-cli
  application-realm: sbcgg
  application-client: sbcgg
  username: keycloak
