services:

  # the core database engine
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: sbcgg-postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "UTC"
    volumes:
      - ../configs/postgres:/docker-entrypoint-initdb.d:z
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M

  # Identity and Access Management
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.3
    container_name: sbcgg-keycloak
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:8080" # https://github.com/keycloak/keycloak/issues/42739
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      TZ: UTC
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
    command: [ "start-dev", "--import-realm" ]
    healthcheck:
      test: # https://gist.github.com/sarath-soman/5d9aec06953bbd0990c648605d4dba07?permalink_comment_id=5821829#gistcomment-5821829
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/localhost/9000; \
                echo -en 'GET /health/ready' >&3; \
                # Give the server a moment to respond, then search for 'UP'
                if timeout 3 cat <&3 | grep -m 1 'UP'; then \
                  exec 3<&-; exec 3>&-; exit 0; \
                else \
                  exec 3<&-; exec 3>&-; exit 1; \
                fi"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    volumes:
      - ../configs/keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M

  # shared cache, rate limiting, pub/sub, ...
  redis:
    image: redis:8.6.0-alpine3.23
    command: redis-server --requirepass redis --loglevel warning
    container_name: sbcgg-redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "redis", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M