spring:
  application:
    name: messages-service
  grpc:
    client:
      channels:
        users:
          negotiation-type: PLAINTEXT

service:
  messages:
    max-retries: 5
    next-attempt-wait-duration: 30s
