server:
  port: 8190

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/messages?cachePrepStmts=true&useServerPrepStmts=true
    username: postgres
    password: postgres
  devtools:
    livereload:
      port: 35731
  data:
    redis:
      host: localhost
      password: redis
  config:
    import:
      - "optional:classpath:config/jpa/application.yaml"
      - "optional:classpath:config/app/application.yaml"
      - "optional:classpath:config/app/application-dev.yaml"
  grpc:
    server:
      port: 8191
    client:
      channels:
        users:
          address: "static://localhost:8091"
