spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/messages?cachePrepStmts=true&useServerPrepStmts=true
    username: postgres
    password: "" # from config server
  data:
    redis:
      host: redis
      password: "" # from config server
  cloud:
    consul:
      host: consul
      config:
        enabled: true
        format: YAML
        fail-fast: true
  config:
    import:
      - "optional:consul:"
      - "optional:classpath:config/jpa/application.yaml"
      - "optional:classpath:config/app/application.yaml"
      - "optional:classpath:config/app/application-dev-docker.yaml"
  grpc:
    client:
      channels:
        users:
          address: "discovery:///users-service"

otel:
  exporter:
    otlp:
      endpoint: http://lgtm:4318
