spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    add-properties: false
  cloud:
    consul:
      host: consul
      config:
        enabled: true
        format: YAML
        fail-fast: true
      discovery:
        enabled: true
        register: true
        fail-fast: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 10s
        health-check-critical-timeout: 30s