apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: sbcgg
  labels:
    app: consul
    app.kubernetes.io/name: consul
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: sbcgg-platform
spec:
  type: ClusterIP
  ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
      name: http
    - port: 8600
      targetPort: 8600
      protocol: TCP
      name: dns-tcp
    - port: 8600
      targetPort: 8600
      protocol: UDP
      name: dns-udp
  selector:
    app: consul
