apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: sbcgg
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: sbcgg-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gateway
