apiVersion: v1
kind: Service
metadata:
  name: messages-service
  namespace: sbcgg
  labels:
    app: messages-service
    app.kubernetes.io/name: messages-service
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: sbcgg-platform
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8191
    targetPort: 8191
    protocol: TCP
    name: grpc
  selector:
    app: messages-service
